<?php

declare(strict_types=1);

namespace Kumwe\App\Tests\Unit\Infrastructure\Mcp;

use Kumwe\App\Infrastructure\Mcp\McpCapabilityCatalog;
use Kumwe\App\Infrastructure\Mcp\McpJsonSchemaNormalizer;
use Kumwe\App\Infrastructure\Mcp\McpMachineContract;
use Kumwe\App\Infrastructure\Mcp\McpToolErrorVocabulary;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use RuntimeException;

/**
 * Proves the retained compatibility fixture is generated from the live catalogue and remains coherent.
 *
 * @since  2.0.0
 */
#[CoversClass(McpMachineContract::class)]
#[CoversClass(McpJsonSchemaNormalizer::class)]
#[CoversClass(McpToolErrorVocabulary::class)]
final class McpMachineContractTest extends TestCase
{
    /**
     * Freeze exact generated bytes, counts and the canonical compatibility digest.
     *
     * @return  void
     *
     * @since   2.0.0
     */
    public function testRetainedFixtureMatchesTheLiveCatalogueExactly(): void
    {
        $contract = new McpMachineContract(new McpCapabilityCatalog());
        $document = $contract->document();
        $fixture = dirname(__DIR__, 4) . '/docs/machine-contract/mcp-v1.json';

        self::assertSame(
            McpMachineContract::prettyJson($document),
            file_get_contents($fixture),
        );
        self::assertSame(
            ['tools' => 75, 'resources' => 1, 'prompts' => 1],
            $document['inventory'],
        );
        self::assertSame(
            hash('sha256', McpMachineContract::canonicalJson([
                'surface' => $document['surface'],
                'tool_error' => $document['tool_error'],
            ])),
            $document['contract_sha256'],
        );
        self::assertSame('retained', $document['generation']['status']);
    }

    /**
     * Pin the dependency version and source reference the protocol fixture was generated against.
     *
     * @return  void
     *
     * @since   2.0.0
     */
    public function testGenerationPinsTheInstalledOfficialSdkRelease(): void
    {
        $lock = json_decode(
            (string) file_get_contents(dirname(__DIR__, 4) . '/composer.lock'),
            true,
            512,
            JSON_THROW_ON_ERROR,
        );
        self::assertIsArray($lock);
        $packages = array_values(array_filter(
            $lock['packages'],
            static fn (array $package): bool => $package['name'] === 'mcp/sdk',
        ));
        self::assertCount(1, $packages);

        $generation = (new McpMachineContract(new McpCapabilityCatalog()))->document()['generation'];
        self::assertSame($packages[0]['version'], $generation['sdk']['version']);
        self::assertSame($packages[0]['source']['reference'], $generation['sdk']['source_reference']);
    }

    /**
     * Bind every mapper code, sentence, retry decision and classification to a retained digest.
     *
     * The exact-fixture assertion above makes a real vocabulary edit fail until it is reviewed as a
     * compatibility change. The local mutation below proves the digest itself covers the registry rather
     * than only the tool catalogue.
     *
     * @return  void
     *
     * @since   2.0.0
     */
    public function testMapperVocabularyIsPartOfTheRetainedContractDigest(): void
    {
        $document = (new McpMachineContract(new McpCapabilityCatalog()))->document();
        $registry = McpToolErrorVocabulary::registry();

        self::assertSame($registry, $document['tool_error']['registry']);
        self::assertSame(
            hash('sha256', McpMachineContract::canonicalJson($registry)),
            $document['tool_error']['registry_sha256'],
        );

        $contractMaterial = [
            'surface' => $document['surface'],
            'tool_error' => $document['tool_error'],
        ];
        foreach (['code', 'message', 'retryable', 'classification'] as $change) {
            $drifted = $contractMaterial;
            if ($change === 'code') {
                $drifted['tool_error']['registry'][0]['code'] = 'authorization.changed';
            } elseif ($change === 'message') {
                $drifted['tool_error']['registry'][0]['message'] = 'A changed mapper sentence.';
            } elseif ($change === 'retryable') {
                $drifted['tool_error']['registry'][0]['retryable'] = true;
            } else {
                $drifted['tool_error']['registry'][0]['classifications'][0]['exception'] = RuntimeException::class;
            }

            self::assertNotSame(
                $document['contract_sha256'],
                hash('sha256', McpMachineContract::canonicalJson($drifted)),
                sprintf('Changing the retained error %s must change the primary contract digest.', $change),
            );
        }
    }

    /**
     * Keep the retained mapper vocabulary finite and free from ambiguous classification rows.
     *
     * @return  void
     *
     * @since   2.0.0
     */
    public function testMapperVocabularyContainsUniqueCodesAndClassifications(): void
    {
        $codes = [];
        $classifications = [];
        foreach (McpToolErrorVocabulary::registry() as $definition) {
            self::assertMatchesRegularExpression('/^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+$/D', $definition['code']);
            self::assertNotSame([], $definition['classifications']);
            $codes[] = $definition['code'];

            foreach ($definition['classifications'] as $classification) {
                $key = $classification['exception'] . "\0" . ($classification['stable_code'] ?? '');
                self::assertArrayNotHasKey($key, $classifications);
                $classifications[$key] = true;
            }
        }

        self::assertSame($codes, array_values(array_unique($codes)));
    }

    /**
     * Require exclusions to remain explicit, uniquely identified and absent from live registration.
     *
     * @return  void
     *
     * @since   2.0.0
     */
    public function testEveryIntentionalExclusionIsStructuredAndActuallyExcluded(): void
    {
        $document = (new McpMachineContract(new McpCapabilityCatalog()))->document();
        $registered = array_column($document['surface']['tools'], 'name');
        $identifiers = [];

        foreach ($document['intentional_exclusions'] as $exclusion) {
            self::assertSame(['id', 'operations', 'control', 'alternatives'], array_keys($exclusion));
            self::assertNotSame('', $exclusion['id']);
            self::assertNotSame([], $exclusion['operations']);
            self::assertNotSame('', $exclusion['control']);
            self::assertNotSame([], $exclusion['alternatives']);
            foreach ($exclusion['operations'] as $operation) {
                self::assertNotContains($operation, $registered);
            }
            $identifiers[] = $exclusion['id'];
        }

        self::assertSame($identifiers, array_values(array_unique($identifiers)));
    }

    /**
     * Preserve empty vocabulary lists while encoding every empty schema position as a JSON object.
     *
     * @return  void
     *
     * @since   2.0.0
     */
    public function testSchemaNormalizationDistinguishesObjectsFromListsRecursively(): void
    {
        $schema = McpJsonSchemaNormalizer::normalize([
            'type' => 'object',
            'properties' => [
                'anything' => [],
                'values' => ['type' => 'array', 'items' => []],
            ],
            'required' => [],
            'allOf' => [],
        ]);
        $wire = json_encode($schema, JSON_THROW_ON_ERROR);

        self::assertStringContainsString('"anything":{}', $wire);
        self::assertStringContainsString('"items":{}', $wire);
        self::assertStringContainsString('"required":[]', $wire);
        self::assertStringContainsString('"allOf":[]', $wire);
    }
}
