<?php

/**
 * Compiled interface message catalogue for en-GB, carrying 89 messages.
 *
 * Generated from en-GB.xlf by `composer translation:compile`. Do not edit: the build
 * compares these bytes against a fresh compilation and fails when they differ. Author the
 * change in the XLIFF source, which is what a translator and a translation platform read.
 *
 * @since  2.0.0
 */

declare(strict_types=1);

return [
    'core.administrator.access_denied.context_title' => 'Access denied',
    'core.administrator.access_denied.dashboard_action' => 'Back to the dashboard',
    'core.administrator.access_denied.document_title' => 'Access denied · Kumwe',
    'core.administrator.access_denied.explanation' => 'Your account is missing the <code>{capability}</code> capability, so this screen stays closed. Everything you are permitted to use is listed in the navigation.',
    'core.administrator.access_denied.eyebrow' => 'Permissions',
    'core.administrator.access_denied.heading' => 'You do not have access to this screen',
    'core.administrator.access_denied.next_explanation' => 'Pick a screen from the navigation, or return to your dashboard.',
    'core.administrator.access_denied.next_heading' => 'Where to go next',
    'core.administrator.access_denied.request_access' => 'If your work needs this screen, ask an administrator with user management access to grant the <code>{capability}</code> capability to your role.',
    'core.administrator.extension_error.context_title' => 'Extension unavailable',
    'core.administrator.extension_error.document_title' => 'Extension unavailable · Kumwe',
    'core.administrator.extension_error.explanation' => 'The requested extension view could not be rendered safely.',
    'core.administrator.extension_error.eyebrow' => 'Extension',
    'core.administrator.extension_error.heading' => 'Extension view unavailable',
    'core.administrator.layout.brand_role' => 'Administrator',
    'core.administrator.layout.close_navigation' => 'Close administrator navigation',
    'core.administrator.layout.context_subtitle' => 'Manage your website with confidence',
    'core.administrator.layout.context_title' => 'Administrator workspace',
    'core.administrator.layout.document_title' => 'Kumwe Administrator',
    'core.administrator.layout.navigation_label' => 'Administrator navigation',
    'core.administrator.layout.open_navigation' => 'Open administrator navigation',
    'core.administrator.layout.search' => 'Search administrator',
    'core.administrator.layout.sign_out' => 'Sign out',
    'core.administrator.layout.skip_to_content' => 'Skip to content',
    'core.administrator.layout.view_website' => 'View website',
    'core.administrator.login.document_title' => 'Sign in · Kumwe',
    'core.administrator.login.email_label' => 'Email address',
    'core.administrator.login.eyebrow' => 'Welcome back',
    'core.administrator.login.footer' => 'Protected administrator area · Sessions and permission decisions are audited',
    'core.administrator.login.heading' => 'Sign in',
    'core.administrator.login.password_label' => 'Password',
    'core.administrator.login.purpose' => 'Manage content, publishing, navigation and the platform from one secure workspace.',
    'core.administrator.login.submit' => 'Sign in to Kumwe',
    'core.interface_standard.drawer.close' => 'Close',
    'core.interface_standard.master_detail.catalog_toggle' => 'Browse resources',
    'core.interface_standard.report_parameter.choose_boolean' => 'Choose yes or no',
    'core.interface_standard.report_parameter.help' => '{type}{multiple, select, true {; enter one value per line, up to {limit, number}} other {}}{optional, select, true {; optional} other {}}.',
    'core.interface_standard.report_parameter.no' => 'No',
    'core.interface_standard.report_parameter.none_required' => 'No parameters are required. Run the report to use its declared scope.',
    'core.interface_standard.report_parameter.use_default' => 'Use report default',
    'core.interface_standard.report_parameter.yes' => 'Yes',
    'core.interface_standard.technical_value.copy' => 'Copy',
    'core.interface_standard.technical_value.copy_label' => 'Copy {label}',
    'core.interface_standard.technical_value.default_label' => 'technical value',
    'core.interface_standard.technical_value.label_prefix' => '{label}: ',
    'core.interface_standard.validation_summary.title' => 'Review the highlighted fields',
    'core.portal.layout.brand_home' => 'Kumwe Portal home',
    'core.portal.layout.brand_role' => 'Portal',
    'core.portal.layout.context_label' => 'Active portal context',
    'core.portal.layout.document_title' => 'Kumwe Portal',
    'core.portal.layout.navigation_label' => 'Portal navigation',
    'core.portal.layout.sign_out' => 'Sign out',
    'core.portal.layout.skip_to_content' => 'Skip to main content',
    'core.portal.login.document_title' => 'Sign in · Kumwe Portal',
    'core.portal.login.email_label' => 'Email address',
    'core.portal.login.eyebrow' => 'Business workspace',
    'core.portal.login.heading' => 'Sign in to the portal',
    'core.portal.login.help_closing' => 'If sign-in is unavailable, ask your administrator to review the complete provisioning path. For your security, this page does not reveal which identity or access prerequisite is missing.',
    'core.portal.login.help_identifier' => 'The exact workspace identifier, only when your administrator asks you to enter one.',
    'core.portal.login.help_identity' => 'Your own active user identity — never a shared account.',
    'core.portal.login.help_intro' => 'An administrator must provision each part of portal access before you sign in:',
    'core.portal.login.help_membership' => 'An active membership in the organization.',
    'core.portal.login.help_summary' => 'What access do I need?',
    'core.portal.login.help_workspace' => 'A permitted workspace and the roles needed for your work.',
    'core.portal.login.password_label' => 'Password',
    'core.portal.login.purpose' => 'Use your Kumwe identity. Your organization and workspace are resolved from active memberships.',
    'core.portal.login.submit' => 'Sign in',
    'core.portal.login.workspace_help' => 'Leave blank to use your default active workspace.',
    'core.portal.login.workspace_label' => 'Workspace <span>(optional)</span>',
    'core.site.article.further_reading' => 'Further reading',
    'core.site.article.highlights' => 'Highlights',
    'core.site.document.contents_heading' => 'On this page',
    'core.site.document.introduction' => 'Introduction',
    'core.site.guide.contents_heading' => 'Steps',
    'core.site.guide.outcome_heading' => 'What you have now',
    'core.site.home.document_title' => 'Site setup · {site}',
    'core.site.home.explanation' => 'The configured homepage is unavailable. Sign in to select or publish a managed page; Kumwe will render that database content here immediately.',
    'core.site.home.eyebrow' => 'Site setup',
    'core.site.home.heading' => 'Choose a published homepage.',
    'core.site.home.placeholder_notice' => 'No placeholder page has replaced your managed content.',
    'core.site.home.settings_action' => 'Open site settings',
    'core.site.layout.document_title' => '{page} · {site}',
    'core.site.layout.footer_fallback' => 'Powered by Kumwe CMS',
    'core.site.layout.main_navigation' => 'Main navigation',
    'core.site.layout.navigation_toggle' => 'Menu',
    'core.site.layout.open_navigation' => 'Open site navigation',
    'core.site.layout.skip_to_content' => 'Skip to content',
    'core.site.reference.contents_heading' => 'In this reference',
    'core.site.reference.example_label' => 'Example for {term}',
];
