<?php

/**
 * Verify the shipped alerting rules, inhibition rules, runbooks, dashboards and promtool scenarios offline.
 *
 * `composer observability:rules` runs this inside `composer qa`. It parses `deploy/observability/alerts.yaml`
 * and `alertmanager.yaml` with a strict reader, parses every expression, and refuses: an unknown series or
 * label, a matcher value outside a label's enumeration, a counter function over a gauge, an unbounded or
 * forbidden label, a result that could mint more than a handful of alerts, a template naming a label the alert
 * does not carry, a runbook section that does not exist, an inhibition rule whose `equal` labels are missing on
 * either side, a dashboard query that fails the same checks or crosses the business/transport split, and an
 * alert without a promtool scenario. It then renders `deploy/observability/tests/alerts.test.yaml` from the
 * scenarios and the rules and refuses a committed copy that differs. CI additionally runs the real
 * `promtool check rules`, `promtool test rules` and `amtool check-config` (see tools/alert-drill.sh).
 *
 * Usage:
 *   php tools/verify-alert-rules.php            check; exit 1 on any problem
 *   php tools/verify-alert-rules.php --write    regenerate the promtool test file, then check
 *
 * @since  2.0.0
 */

declare(strict_types=1);

use Kumwe\App\Infrastructure\Observability\MetricCatalog;
use Kumwe\App\Infrastructure\Observability\ObservabilityContract;
use Kumwe\App\Tools\Observability\DashboardGate;
use Kumwe\App\Tools\Observability\MetricInventory;
use Kumwe\App\Tools\Observability\PromtoolTests;
use Kumwe\App\Tools\Observability\RuleGate;
use Kumwe\App\Tools\Observability\RuleViolation;
use Kumwe\App\Tools\Observability\SyntheticProbe;

require_once __DIR__ . '/Observability/bootstrap.php';

$root = dirname(__DIR__);
$write = in_array('--write', array_slice($argv, 1), true);
foreach (array_slice($argv, 1) as $argument) {
    if ($argument !== '--write') {
        fwrite(STDERR, "Usage: php tools/verify-alert-rules.php [--write]\n");
        exit(64);
    }
}

$contract = ObservabilityContract::load($root);
$inventory = MetricInventory::create(MetricCatalog::create($contract, 'gate', 'http'), SyntheticProbe::CHECKS);
$gate = new RuleGate($root, $inventory, $contract->forbiddenLabels);
$problems = $gate->problems();
$alerts = [];
$testFile = $root . '/deploy/observability/tests/alerts.test.yaml';
try {
    $alerts = RuleGate::load($root . '/deploy/observability/alerts.yaml');
    $scenarios = json_decode((string) file_get_contents($root . '/deploy/observability/tests/scenarios.json'), true);
    if (!is_array($scenarios)) {
        throw RuleViolation::at('deploy/observability/tests/scenarios.json', 'is not a JSON object');
    }
    /** @var array<string, mixed> $scenarios */
    $rendered = PromtoolTests::yaml(
        (new PromtoolTests($alerts, $gate->carried($alerts)))->document($scenarios, '../alerts.yaml'),
    );
    $header = "# Generated by `php tools/verify-alert-rules.php --write` from scenarios.json and ../alerts.yaml.\n"
        . "# Run with: promtool test rules deploy/observability/tests/alerts.test.yaml\n";
    if ($write) {
        file_put_contents($testFile, $header . $rendered);
    }
    if ((string) @file_get_contents($testFile) !== $header . $rendered) {
        $problems[] = 'deploy/observability/tests/alerts.test.yaml: is stale; run `php tools/verify-alert-rules.php --write`.';
    }
} catch (RuleViolation $violation) {
    $problems[] = $violation->getMessage();
}
$dashboards = new DashboardGate($root, $inventory, $contract->forbiddenLabels);
$problems = array_merge($problems, $dashboards->problems());

if ($problems !== []) {
    foreach ($problems as $problem) {
        fwrite(STDERR, 'Observability rules: ' . $problem . "\n");
    }
    exit(1);
}

$pages = count(array_filter($alerts, static fn ($alert): bool => $alert->severity() === 'page'));
printf(
    "Kumwe observability rules verified: %d alerts (%d page), inhibition rules, runbooks, %d dashboards and "
    . "%d promtool scenarios; every label bounded.\n",
    count($alerts),
    $pages,
    count($dashboards->files()),
    count($alerts),
);
