-- Kumwe CMS 2.0 Phase 7 automation schema.
-- PostgreSQL is the durable authority for jobs, scheduling, outbox delivery and
-- idempotency. Identifiers are generated by the application as UUIDv7 values.

BEGIN;

CREATE SCHEMA IF NOT EXISTS {{schema}};

CREATE TABLE {{schema}}.schedules (
    id uuid PRIMARY KEY,
    name varchar(160) NOT NULL,
    cron_expression varchar(120) NOT NULL,
    timezone varchar(80) NOT NULL,
    queue varchar(64) NOT NULL DEFAULT 'default',
    job_type varchar(128) NOT NULL,
    job_schema_version integer NOT NULL DEFAULT 1,
    payload jsonb NOT NULL DEFAULT '{}'::jsonb,
    priority smallint NOT NULL DEFAULT 0,
    maximum_attempts smallint NOT NULL DEFAULT 5,
    enabled boolean NOT NULL DEFAULT true,
    next_run_at timestamptz,
    last_run_at timestamptz,
    version integer NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT uq_kumwe_schedules_name UNIQUE (name),
    CONSTRAINT ck_kumwe_schedules_queue
        CHECK (queue ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$'),
    CONSTRAINT ck_kumwe_schedules_job_type
        CHECK (job_type ~ '^[A-Za-z][A-Za-z0-9._:-]{2,127}$'),
    CONSTRAINT ck_kumwe_schedules_schema_version CHECK (job_schema_version > 0),
    CONSTRAINT ck_kumwe_schedules_payload_shape CHECK (jsonb_typeof(payload) IN ('object', 'array')),
    CONSTRAINT ck_kumwe_schedules_priority CHECK (priority BETWEEN -100 AND 100),
    CONSTRAINT ck_kumwe_schedules_maximum_attempts CHECK (maximum_attempts > 0),
    CONSTRAINT ck_kumwe_schedules_version CHECK (version > 0),
    CONSTRAINT ck_kumwe_schedules_timestamps CHECK (updated_at >= created_at)
);

CREATE INDEX idx_kumwe_schedules_due
    ON {{schema}}.schedules (next_run_at, id)
    WHERE enabled = true AND next_run_at IS NOT NULL;

CREATE TABLE {{schema}}.jobs (
    id uuid PRIMARY KEY,
    queue varchar(64) NOT NULL DEFAULT 'default',
    job_type varchar(128) NOT NULL,
    schema_version integer NOT NULL DEFAULT 1,
    payload jsonb NOT NULL,
    priority smallint NOT NULL DEFAULT 0,
    status varchar(16) NOT NULL DEFAULT 'pending',
    available_at timestamptz NOT NULL,
    lease_owner varchar(128),
    lease_acquired_at timestamptz,
    lease_expires_at timestamptz,
    attempts smallint NOT NULL DEFAULT 0,
    maximum_attempts smallint NOT NULL DEFAULT 5,
    schedule_id uuid REFERENCES {{schema}}.schedules (id) ON DELETE SET NULL,
    scheduled_for timestamptz,
    occurrence_key varchar(128),
    completed_at timestamptz,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CONSTRAINT ck_kumwe_jobs_queue
        CHECK (queue ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$'),
    CONSTRAINT ck_kumwe_jobs_type
        CHECK (job_type ~ '^[A-Za-z][A-Za-z0-9._:-]{2,127}$'),
    CONSTRAINT ck_kumwe_jobs_schema_version CHECK (schema_version > 0),
    CONSTRAINT ck_kumwe_jobs_payload_shape CHECK (jsonb_typeof(payload) IN ('object', 'array')),
    CONSTRAINT ck_kumwe_jobs_priority CHECK (priority BETWEEN -100 AND 100),
    CONSTRAINT ck_kumwe_jobs_status
        CHECK (status IN ('pending', 'reserved', 'completed', 'dead')),
    CONSTRAINT ck_kumwe_jobs_attempts
        CHECK (attempts >= 0 AND maximum_attempts > 0 AND attempts <= maximum_attempts),
    CONSTRAINT ck_kumwe_jobs_pending_attempts
        CHECK (status <> 'pending' OR attempts < maximum_attempts),
    CONSTRAINT ck_kumwe_jobs_lease
        CHECK (
            (status = 'reserved'
                AND lease_owner IS NOT NULL
                AND lease_acquired_at IS NOT NULL
                AND lease_expires_at IS NOT NULL
                AND lease_expires_at > lease_acquired_at)
            OR
            (status <> 'reserved'
                AND lease_owner IS NULL
                AND lease_acquired_at IS NULL
                AND lease_expires_at IS NULL)
        ),
    CONSTRAINT ck_kumwe_jobs_schedule_occurrence
        CHECK (
            (schedule_id IS NULL AND scheduled_for IS NULL AND occurrence_key IS NULL)
            OR
            (schedule_id IS NOT NULL AND scheduled_for IS NOT NULL AND occurrence_key IS NOT NULL)
        ),
    CONSTRAINT ck_kumwe_jobs_occurrence_key
        CHECK (occurrence_key IS NULL OR occurrence_key ~ '^schedule:[a-f0-9]{64}$'),
    CONSTRAINT ck_kumwe_jobs_completion
        CHECK (
            (status = 'completed' AND completed_at IS NOT NULL)
            OR (status <> 'completed' AND completed_at IS NULL)
        ),
    CONSTRAINT ck_kumwe_jobs_terminal_attempt CHECK (status = 'pending' OR attempts > 0),
    CONSTRAINT ck_kumwe_jobs_timestamps
        CHECK (available_at >= created_at AND updated_at >= created_at)
);

CREATE UNIQUE INDEX uq_kumwe_jobs_schedule_occurrence
    ON {{schema}}.jobs (schedule_id, scheduled_for)
    WHERE schedule_id IS NOT NULL;

CREATE UNIQUE INDEX uq_kumwe_jobs_occurrence_key
    ON {{schema}}.jobs (occurrence_key)
    WHERE occurrence_key IS NOT NULL;

CREATE INDEX idx_kumwe_jobs_claim
    ON {{schema}}.jobs (queue, priority DESC, available_at, created_at, id)
    WHERE status = 'pending';

CREATE INDEX idx_kumwe_jobs_expired_leases
    ON {{schema}}.jobs (lease_expires_at, id)
    WHERE status = 'reserved';

CREATE TABLE {{schema}}.failed_jobs (
    id uuid PRIMARY KEY,
    job_id uuid NOT NULL,
    queue varchar(64) NOT NULL,
    job_type varchar(128) NOT NULL,
    schema_version integer NOT NULL,
    payload jsonb NOT NULL,
    attempts smallint NOT NULL,
    maximum_attempts smallint NOT NULL,
    failure_classification varchar(16) NOT NULL,
    exception_type varchar(255) NOT NULL,
    error_message text NOT NULL,
    failed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL,
    CONSTRAINT uq_kumwe_failed_jobs_job UNIQUE (job_id),
    CONSTRAINT ck_kumwe_failed_jobs_payload_shape CHECK (jsonb_typeof(payload) IN ('object', 'array')),
    CONSTRAINT ck_kumwe_failed_jobs_attempts
        CHECK (attempts > 0 AND maximum_attempts > 0 AND attempts <= maximum_attempts),
    CONSTRAINT ck_kumwe_failed_jobs_classification
        CHECK (failure_classification IN ('transient', 'permanent')),
    CONSTRAINT ck_kumwe_failed_jobs_timestamps CHECK (failed_at >= created_at)
);

CREATE INDEX idx_kumwe_failed_jobs_failed_at
    ON {{schema}}.failed_jobs (failed_at DESC, id);

CREATE TABLE {{schema}}.worker_heartbeats (
    worker_id varchar(128) PRIMARY KEY,
    queue varchar(64) NOT NULL,
    process_id integer,
    release varchar(128) NOT NULL,
    started_at timestamptz NOT NULL,
    heartbeat_at timestamptz NOT NULL,
    current_job_id uuid,
    CONSTRAINT ck_kumwe_worker_heartbeats_worker
        CHECK (worker_id ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{2,127}$'),
    CONSTRAINT ck_kumwe_worker_heartbeats_queue
        CHECK (queue ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{0,63}$'),
    CONSTRAINT ck_kumwe_worker_heartbeats_process CHECK (process_id IS NULL OR process_id > 0),
    CONSTRAINT ck_kumwe_worker_heartbeats_time CHECK (heartbeat_at >= started_at)
);

CREATE INDEX idx_kumwe_worker_heartbeats_freshness
    ON {{schema}}.worker_heartbeats (heartbeat_at DESC, worker_id);

CREATE TABLE {{schema}}.outbox (
    id uuid PRIMARY KEY,
    aggregate_type varchar(128) NOT NULL,
    aggregate_id uuid NOT NULL,
    aggregate_version integer NOT NULL,
    event_type varchar(160) NOT NULL,
    event_schema_version integer NOT NULL DEFAULT 1,
    payload jsonb NOT NULL,
    status varchar(16) NOT NULL DEFAULT 'pending',
    available_at timestamptz NOT NULL,
    lease_owner varchar(128),
    lease_acquired_at timestamptz,
    lease_expires_at timestamptz,
    attempts smallint NOT NULL DEFAULT 0,
    maximum_attempts smallint NOT NULL DEFAULT 10,
    occurred_at timestamptz NOT NULL,
    published_at timestamptz,
    created_at timestamptz NOT NULL,
    CONSTRAINT uq_kumwe_outbox_aggregate_event UNIQUE (aggregate_type, aggregate_id, aggregate_version, event_type),
    CONSTRAINT ck_kumwe_outbox_aggregate_version CHECK (aggregate_version > 0),
    CONSTRAINT ck_kumwe_outbox_event_schema_version CHECK (event_schema_version > 0),
    CONSTRAINT ck_kumwe_outbox_payload_object CHECK (jsonb_typeof(payload) = 'object'),
    CONSTRAINT ck_kumwe_outbox_status
        CHECK (status IN ('pending', 'reserved', 'published', 'dead')),
    CONSTRAINT ck_kumwe_outbox_attempts
        CHECK (attempts >= 0 AND maximum_attempts > 0 AND attempts <= maximum_attempts),
    CONSTRAINT ck_kumwe_outbox_pending_attempts
        CHECK (status <> 'pending' OR attempts < maximum_attempts),
    CONSTRAINT ck_kumwe_outbox_lease
        CHECK (
            (status = 'reserved'
                AND lease_owner IS NOT NULL
                AND lease_acquired_at IS NOT NULL
                AND lease_expires_at IS NOT NULL
                AND lease_expires_at > lease_acquired_at)
            OR
            (status <> 'reserved'
                AND lease_owner IS NULL
                AND lease_acquired_at IS NULL
                AND lease_expires_at IS NULL)
        ),
    CONSTRAINT ck_kumwe_outbox_published
        CHECK (
            (status = 'published' AND published_at IS NOT NULL)
            OR (status <> 'published' AND published_at IS NULL)
        ),
    CONSTRAINT ck_kumwe_outbox_time
        CHECK (created_at >= occurred_at AND available_at >= occurred_at)
);

CREATE INDEX idx_kumwe_outbox_claim
    ON {{schema}}.outbox (available_at, occurred_at, id)
    WHERE status = 'pending';

CREATE INDEX idx_kumwe_outbox_expired_leases
    ON {{schema}}.outbox (lease_expires_at, id)
    WHERE status = 'reserved';

CREATE TABLE {{schema}}.idempotency (
    id uuid PRIMARY KEY,
    idempotency_key varchar(128) NOT NULL,
    subject varchar(255) NOT NULL,
    operation varchar(160) NOT NULL,
    request_digest char(64) NOT NULL,
    state varchar(16) NOT NULL DEFAULT 'in_progress',
    result_status smallint,
    result_body jsonb,
    result_body_digest char(64),
    created_at timestamptz NOT NULL,
    completed_at timestamptz,
    expires_at timestamptz NOT NULL,
    CONSTRAINT uq_kumwe_idempotency_scope UNIQUE (subject, operation, idempotency_key),
    CONSTRAINT ck_kumwe_idempotency_key
        CHECK (idempotency_key ~ '^[A-Za-z0-9][A-Za-z0-9._:-]{7,127}$'),
    CONSTRAINT ck_kumwe_idempotency_request_digest CHECK (request_digest ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_kumwe_idempotency_state
        CHECK (state IN ('in_progress', 'completed', 'failed')),
    CONSTRAINT ck_kumwe_idempotency_result_status
        CHECK (result_status IS NULL OR result_status BETWEEN 100 AND 599),
    CONSTRAINT ck_kumwe_idempotency_result_digest
        CHECK (result_body_digest IS NULL OR result_body_digest ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_kumwe_idempotency_result
        CHECK (
            (state = 'completed'
                AND result_status IS NOT NULL
                AND result_body IS NOT NULL
                AND result_body_digest IS NOT NULL
                AND completed_at IS NOT NULL)
            OR
            (state <> 'completed'
                AND result_status IS NULL
                AND result_body IS NULL
                AND result_body_digest IS NULL
                AND completed_at IS NULL)
        ),
    CONSTRAINT ck_kumwe_idempotency_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_kumwe_idempotency_expiry
    ON {{schema}}.idempotency (expires_at, id);

CREATE INDEX idx_kumwe_idempotency_in_progress
    ON {{schema}}.idempotency (created_at, id)
    WHERE state = 'in_progress';

CREATE TABLE {{schema}}.api_tokens (
    id uuid PRIMARY KEY,
    subject_id uuid NOT NULL REFERENCES {{schema}}.users (id) ON DELETE CASCADE,
    token_digest char(64) NOT NULL UNIQUE,
    name varchar(191) NOT NULL,
    capabilities jsonb NOT NULL DEFAULT '[]'::jsonb,
    expires_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at timestamptz,
    CONSTRAINT ck_kumwe_api_tokens_digest CHECK (token_digest ~ '^[a-f0-9]{64}$'),
    CONSTRAINT ck_kumwe_api_tokens_name CHECK (btrim(name) <> ''),
    CONSTRAINT ck_kumwe_api_tokens_capabilities CHECK (jsonb_typeof(capabilities) = 'array'),
    CONSTRAINT ck_kumwe_api_tokens_expiry CHECK (expires_at IS NULL OR expires_at > created_at),
    CONSTRAINT ck_kumwe_api_tokens_revocation CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT ck_kumwe_api_tokens_last_used CHECK (last_used_at IS NULL OR last_used_at >= created_at)
);

CREATE INDEX idx_kumwe_api_tokens_subject ON {{schema}}.api_tokens (subject_id, created_at DESC);
CREATE INDEX idx_kumwe_api_tokens_expiry
    ON {{schema}}.api_tokens (expires_at)
    WHERE revoked_at IS NULL AND expires_at IS NOT NULL;

COMMIT;
